### PR TITLE
Seq2seq

### PR DESCRIPTION
**Pull request by TorbenSDJohansen**
This PR implements a seq2seq-style `OccCANINE` model. Further, a vanilla loss fn is implemented for testing purposes and the core components of the train and eval loop have been implemented

Several things are still missing before this becomes directly usable. First, some work on the data loading side is required. Second, a new entry-point to reflect the seq2seq-style approach should be built. Third, an AR decoding scheme (e.g., greedy) needs to be developed before inference is possible. However, as those are not directly related to the core seq2seq model components, I plan to implement those in a new branch

### CODE REVIEW

**Comment by christianvedels** [comment]
Great work! It is not clear to me what `class Seq2SeqOccCANINEWrapper(OccCANINE)` is intended for. Is it supposed to be used in training (which would diverge from the current structure - but quite reasonably) or for inference with a similar functionality as the class it inherits from? Or both?

**Comment by TorbenSDJohansen** [comment]
`Seq2SeqOccCANINEWrapper` is not intended to be used for training, but is rather an early version of a wrapper class around the model similar to how `OccCANINE` is a wrapper around the old model. That is, it is a work in progress for inheriting as much as possible from `OccCANINE` when we want to extend the functionality of the new model for inference, fine-tuning, etc.

A point could be made to not follow this pattern (and instead keep things more modular and not have one class responsible for this much), in which case I'd be happy to revert the work on `Seq2SeqOccCANINEWrapper`.

**Comment by christianvedels** [comment]
I think the most user friendly option would be that either version of `OccCANINE` can be loaded from simply calling `OccCANINE()` with appropriate arguments. But this might require that we refactor this class at some point.

**Comment by TorbenSDJohansen** [comment]
Handling everything inside the model itself would break with, e.g., HF pattern, where things like tokenization, IO, etc., is (often) not handled within the model class. I think a better approach would be to either use a wrapper class (as now, but perhaps re-designed) or a pattern where the model is used with other functions and classes (as is very common), handled by the entry-point script.

Bundling everything within the model class will also make it significantly more challenging to extend the code to other models, tasks, etc.,

**Comment by christianvedels** [comment]
Alright. Let's keep it like this for now then.

**Pull request merged**
